In [2]:
import pytrends
from pytrends.request import TrendReq
import pandas as pd
from pandas import DataFrame, Series
import numpy as np
import json

In [3]:
def retrieve_google_trends(start_date='2017-04-18', end_date='', geo='UK'):
    if end_date == '':
        import datetime as dt
        end_date = str(dt.datetime.today())[:10]
    period = start_date + ' ' + end_date
    pytrend = TrendReq('gmail', 'password', custom_useragent='My Pytrends Script')
    pytrend.build_payload(kw_list=['conservatives+conservative party+tories', 'labour party', 'liberal democrats+lib dems+lib dem', 'Green Party'] ,timeframe=period)
    # 'labour party', 'jeremy corbyn', 'nicola sturgeon', 'scottish national party', 'snp', 'tim farron', 'liberal democrats', 'lib dems', 'lib dem', 'Caroline Lucas', 'Jonathan Bartley', 'Green Party', 'Paul Nuttall', 'UK Independence Party', 'UKIP'
    return pytrend.interest_over_time()

In [4]:
data = retrieve_google_trends()

In [5]:
data

,conservatives+conservative party+tories,labour party,liberal democrats+lib dems+lib dem,Green Party
date,,,,
2017-04-18,53,42,100,33
2017-04-19,53,33,69,26
2017-04-20,47,32,43,28
2017-04-21,36,26,37,22
2017-04-22,32,22,26,15
2017-04-23,34,20,33,19
2017-04-24,40,20,32,23
2017-04-25,36,17,27,21
2017-04-26,36,19,28,22
2017-04-27,38,17,23,28
2017-04-28,29,15,18,22
2017-04-29,24,11,16,18
2017-04-30,29,14,21,21
2017-05-01,33,19,18,24
2017-05-02,33,22,18,23
2017-05-03,37,20,28,28
2017-05-04,44,30,38,40
2017-05-05,68,33,35,33
2017-05-06,40,18,19,21
2017-05-07,35,17,17,18
2017-05-08,40,23,26,26
2017-05-09,46,49,22,36
2017-05-10,52,23,21,46
2017-05-11,42,28,24,28
2017-05-12,37,24,39,26
2017-05-13,29,23,22,17
2017-05-14,31,19,22,15
2017-05-15,44,27,24,19
2017-05-16,49,41,27,21
2017-05-17,51,29,73,24
2017-05-18,82,30,48,33
2017-05-19,61,25,31,23
2017-05-20,47,23,30,19
2017-05-21,54,28,24,21

In [6]:
clsld = DataFrame(data)

In [7]:
clsld.columns = ['Conservative Party', 'Labour Party', 'Liberal Democrats', 'Green Party']

In [8]:
clsld

            Conservative Party  Labour Party  Liberal Democrats  Green Party
date
2017-04-18                  53            42                100           33
2017-04-19                  53            33                 69           26
2017-04-20                  47            32                 43           28
2017-04-21                  36            26                 37           22
2017-04-22                  32            22                 26           15
2017-04-23                  34            20                 33           19
2017-04-24                  40            20                 32           23
2017-04-25                  36            17                 27           21
2017-04-26                  36            19                 28           22
2017-04-27                  38            17                 23           28
2017-04-28                  29            15                 18           22
2017-04-29                  24            11                 16           18
2017-04-30                  29            14                 21           21
2017-05-01                  33            19                 18           24
2017-05-02                  33            22                 18           23
2017-05-03                  37            20                 28           28
2017-05-04                  44            30                 38           40
2017-05-05                  68            33                 35           33
2017-05-06                  40            18                 19           21
2017-05-07                  35            17                 17           18
2017-05-08                  40            23                 26           26
2017-05-09                  46            49                 22           36
2017-05-10                  52            23                 21           46
2017-05-11                  42            28                 24           28
2017-05-12                  37            24                 39           26
2017-05-13                  29            23                 22           17
2017-05-14                  31            19                 22           15
2017-05-15                  44            27                 24           19
2017-05-16                  49            41                 27           21
2017-05-17                  51            29                 73           24
2017-05-18                  82            30                 48           33
2017-05-19                  61            25                 31           23
2017-05-20                  47            23                 30           19
2017-05-21                  54            28                 24           21

In [9]:
def retrieve_google_trends(start_date='2017-04-18', end_date='', geo='UK'):
    if end_date == '':
        import datetime as dt
        end_date = str(dt.datetime.today())[:10]
    period = start_date + ' ' + end_date
    pytrend = TrendReq('gmail', 'password', custom_useragent='My Pytrends Script')
    pytrend.build_payload(kw_list=['conservatives+conservative party+tories', 'labour party', 'scottish national party+snp','UK Independence Party+UKIP'] ,timeframe=period)
    # 'labour party', 'jeremy corbyn', 'nicola sturgeon', 'scottish national party', 'snp', 'tim farron', 'liberal democrats', 'lib dems', 'lib dem', 'Caroline Lucas', 'Jonathan Bartley', 'Green Party', 'Paul Nuttall', 'UK Independence Party', 'UKIP'
    return pytrend.interest_over_time()

In [10]:
data1 = retrieve_google_trends()

In [11]:
data1

,conservatives+conservative party+tories,labour party,scottish national party+snp,UK Independence Party+UKIP
date,,,,
2017-04-18,65,51,58,32
2017-04-19,64,40,51,20
2017-04-20,57,39,43,19
2017-04-21,44,31,35,13
2017-04-22,39,26,31,19
2017-04-23,41,25,31,32
2017-04-24,48,25,39,40
2017-04-25,44,21,36,20
2017-04-26,44,23,35,15
2017-04-27,46,21,33,16
2017-04-28,35,18,31,19
2017-04-29,29,13,24,29
2017-04-30,36,17,26,14
2017-05-01,39,23,27,11
2017-05-02,40,26,29,15
2017-05-03,45,24,37,15
2017-05-04,53,37,45,20
2017-05-05,83,40,73,83
2017-05-06,48,22,42,29
2017-05-07,42,21,30,18
2017-05-08,49,27,33,19
2017-05-09,56,59,32,13
2017-05-10,63,28,32,13
2017-05-11,51,34,31,18
2017-05-12,45,29,33,15
2017-05-13,36,28,22,11
2017-05-14,38,24,23,11
2017-05-15,53,33,31,13
2017-05-16,59,50,33,14
2017-05-17,62,35,30,16
2017-05-18,100,36,41,22
2017-05-19,75,31,34,22
2017-05-20,57,28,21,17
2017-05-21,66,35,27,17

In [12]:
clsu = DataFrame(data1)

In [13]:
clsu

,conservatives+conservative party+tories,labour party,scottish national party+snp,UK Independence Party+UKIP
date,,,,
2017-04-18,65,51,58,32
2017-04-19,64,40,51,20
2017-04-20,57,39,43,19
2017-04-21,44,31,35,13
2017-04-22,39,26,31,19
2017-04-23,41,25,31,32
2017-04-24,48,25,39,40
2017-04-25,44,21,36,20
2017-04-26,44,23,35,15
2017-04-27,46,21,33,16
2017-04-28,35,18,31,19
2017-04-29,29,13,24,29
2017-04-30,36,17,26,14
2017-05-01,39,23,27,11
2017-05-02,40,26,29,15
2017-05-03,45,24,37,15
2017-05-04,53,37,45,20
2017-05-05,83,40,73,83
2017-05-06,48,22,42,29
2017-05-07,42,21,30,18
2017-05-08,49,27,33,19
2017-05-09,56,59,32,13
2017-05-10,63,28,32,13
2017-05-11,51,34,31,18
2017-05-12,45,29,33,15
2017-05-13,36,28,22,11
2017-05-14,38,24,23,11
2017-05-15,53,33,31,13
2017-05-16,59,50,33,14
2017-05-17,62,35,30,16
2017-05-18,100,36,41,22
2017-05-19,75,31,34,22
2017-05-20,57,28,21,17
2017-05-21,66,35,27,17

In [14]:
clsu.columns = ['Conservative Party 1', 'Labour Party 1', 'Scottish National Party', 'UK Independence Party']

In [15]:
clsu

,Conservative Party 1,Labour Party 1,Scottish National Party,UK Independence Party
date,,,,
2017-04-18,65,51,58,32
2017-04-19,64,40,51,20
2017-04-20,57,39,43,19
2017-04-21,44,31,35,13
2017-04-22,39,26,31,19
2017-04-23,41,25,31,32
2017-04-24,48,25,39,40
2017-04-25,44,21,36,20
2017-04-26,44,23,35,15
2017-04-27,46,21,33,16
2017-04-28,35,18,31,19
2017-04-29,29,13,24,29
2017-04-30,36,17,26,14
2017-05-01,39,23,27,11
2017-05-02,40,26,29,15
2017-05-03,45,24,37,15
2017-05-04,53,37,45,20
2017-05-05,83,40,73,83
2017-05-06,48,22,42,29
2017-05-07,42,21,30,18
2017-05-08,49,27,33,19
2017-05-09,56,59,32,13
2017-05-10,63,28,32,13
2017-05-11,51,34,31,18
2017-05-12,45,29,33,15
2017-05-13,36,28,22,11
2017-05-14,38,24,23,11
2017-05-15,53,33,31,13
2017-05-16,59,50,33,14
2017-05-17,62,35,30,16
2017-05-18,100,36,41,22
2017-05-19,75,31,34,22
2017-05-20,57,28,21,17
2017-05-21,66,35,27,17

In [16]:
frames = [clsld, clsu]
result = pd.concat(frames, axis=1)

In [17]:
result

,Conservative Party,Labour Party,Liberal Democrats,Green Party,Conservative Party 1,Labour Party 1,Scottish National Party,UK Independence Party
date,,,,,,,,
2017-04-18,53,42,100,33,65,51,58,32
2017-04-19,53,33,69,26,64,40,51,20
2017-04-20,47,32,43,28,57,39,43,19
2017-04-21,36,26,37,22,44,31,35,13
2017-04-22,32,22,26,15,39,26,31,19
2017-04-23,34,20,33,19,41,25,31,32
2017-04-24,40,20,32,23,48,25,39,40
2017-04-25,36,17,27,21,44,21,36,20
2017-04-26,36,19,28,22,44,23,35,15
2017-04-27,38,17,23,28,46,21,33,16
2017-04-28,29,15,18,22,35,18,31,19
2017-04-29,24,11,16,18,29,13,24,29
2017-04-30,29,14,21,21,36,17,26,14
2017-05-01,33,19,18,24,39,23,27,11
2017-05-02,33,22,18,23,40,26,29,15
2017-05-03,37,20,28,28,45,24,37,15
2017-05-04,44,30,38,40,53,37,45,20
2017-05-05,68,33,35,33,83,40,73,83
2017-05-06,40,18,19,21,48,22,42,29
2017-05-07,35,17,17,18,42,21,30,18
2017-05-08,40,23,26,26,49,27,33,19
2017-05-09,46,49,22,36,56,59,32,13
2017-05-10,52,23,21,46,63,28,32,13
2017-05-11,42,28,24,28,51,34,31,18
2017-05-12,37,24,39,26,45,29,33,15
2017-05-13,29,23,22,17,36,28,22,11
2017-05-14,31,19,22,15,38,24,23,11
2017-05-15,44,27,24,19,53,33,31,13
2017-05-16,49,41,27,21,59,50,33,14
2017-05-17,51,29,73,24,62,35,30,16
2017-05-18,82,30,48,33,100,36,41,22
2017-05-19,61,25,31,23,75,31,34,22
2017-05-20,47,23,30,19,57,28,21,17
2017-05-21,54,28,24,21,66,35,27,17

In [18]:
parties = result.drop(['Conservative Party 1', 'Labour Party 1'], axis=1)

In [65]:
parties = parties.drop(['index'], axis=1)

In [67]:
parties.reset_index(inplace=True)

In [68]:
parties

,date,Conservative Party,Labour Party,Liberal Democrats,Green Party,Scottish National Party,UK Independence Party
0,2017-04-18,53,42,100,33,58,32
1,2017-04-19,53,33,69,26,51,20
2,2017-04-20,47,32,43,28,43,19
3,2017-04-21,36,26,37,22,35,13
4,2017-04-22,32,22,26,15,31,19
5,2017-04-23,34,20,33,19,31,32
6,2017-04-24,40,20,32,23,39,40
7,2017-04-25,36,17,27,21,36,20
8,2017-04-26,36,19,28,22,35,15
9,2017-04-27,38,17,23,28,33,16
10,2017-04-28,29,15,18,22,31,19
11,2017-04-29,24,11,16,18,24,29
12,2017-04-30,29,14,21,21,26,14
13,2017-05-01,33,19,18,24,27,11
14,2017-05-02,33,22,18,23,29,15
15,2017-05-03,37,20,28,28,37,15
16,2017-05-04,44,30,38,40,45,20
17,2017-05-05,68,33,35,33,73,83
18,2017-05-06,40,18,19,21,42,29
19,2017-05-07,35,17,17,18,30,18
20,2017-05-08,40,23,26,26,33,19
21,2017-05-09,46,49,22,36,32,13
22,2017-05-10,52,23,21,46,32,13
23,2017-05-11,42,28,24,28,31,18
24,2017-05-12,37,24,39,26,33,15
25,2017-05-13,29,23,22,17,22,11
26,2017-05-14,31,19,22,15,23,11
27,2017-05-15,44,27,24,19,31,13
28,2017-05-16,49,41,27,21,33,14
29,2017-05-17,51,29,73,24,30,16
30,2017-05-18,82,30,48,33,41,22
31,2017-05-19,61,25,31,23,34,22
32,2017-05-20,47,23,30,19,21,17
33,2017-05-21,54,28,24,21,27,17

In [69]:
fparties = parties[parties.date > '2017-04-18']

In [70]:
fparties

,date,Conservative Party,Labour Party,Liberal Democrats,Green Party,Scottish National Party,UK Independence Party
1,2017-04-19,53,33,69,26,51,20
2,2017-04-20,47,32,43,28,43,19
3,2017-04-21,36,26,37,22,35,13
4,2017-04-22,32,22,26,15,31,19
5,2017-04-23,34,20,33,19,31,32
6,2017-04-24,40,20,32,23,39,40
7,2017-04-25,36,17,27,21,36,20
8,2017-04-26,36,19,28,22,35,15
9,2017-04-27,38,17,23,28,33,16
10,2017-04-28,29,15,18,22,31,19
11,2017-04-29,24,11,16,18,24,29
12,2017-04-30,29,14,21,21,26,14
13,2017-05-01,33,19,18,24,27,11
14,2017-05-02,33,22,18,23,29,15
15,2017-05-03,37,20,28,28,37,15
16,2017-05-04,44,30,38,40,45,20
17,2017-05-05,68,33,35,33,73,83
18,2017-05-06,40,18,19,21,42,29
19,2017-05-07,35,17,17,18,30,18
20,2017-05-08,40,23,26,26,33,19
21,2017-05-09,46,49,22,36,32,13
22,2017-05-10,52,23,21,46,32,13
23,2017-05-11,42,28,24,28,31,18
24,2017-05-12,37,24,39,26,33,15
25,2017-05-13,29,23,22,17,22,11
26,2017-05-14,31,19,22,15,23,11
27,2017-05-15,44,27,24,19,31,13
28,2017-05-16,49,41,27,21,33,14
29,2017-05-17,51,29,73,24,30,16
30,2017-05-18,82,30,48,33,41,22
31,2017-05-19,61,25,31,23,34,22
32,2017-05-20,47,23,30,19,21,17
33,2017-05-21,54,28,24,21,27,17

In [71]:
import plotly.plotly as py
from plotly.graph_objs import *
import plotly.graph_objs as go
import cufflinks as cf

In [72]:
p = [o for o in fparties.columns if o <> 'date']

In [73]:
p

['Conservative Party',
 'Labour Party',
 'Liberal Democrats',
 'Green Party',
 'Scottish National Party',
 'UK Independence Party']

In [74]:
pc = {'Conservative Party': "('rgb(0,135,220)')",
    'Labour Party': "('rgb(146,0,13)')",
    'Liberal Democrats': "('rgb(250,166,26)')",
    'Green Party': "('rgb(0,116,95)')",
    'Scottish National Party': "('rgb(255,249,93)')",
    'UK Independence Party': "('rgb(183,0,157)')"}

In [75]:
fig = {
    'data': [
        { 'x': fparties.date,
         'y': fparties[pp],
         'name':pp,
         'mode': 'lines',
         'line': {
             'color': pc [pp]
         }
         } for pp in p
    ]
}

In [76]:
layout = go.Layout(
    plot_bgcolor='rgb(255,255,255)')
    
py.iplot(fig, layout=layout)
#parties.iplot(layout=layout, kind='scatter', colors=['blue', 'red', 'yellow', 'green', 'orange', 'purple'])

In [355]:
trace_con = Bar(x=parties.index,
                  y=parties['Conservative Party'],
                  name='Conservatives',
                  marker=dict(color='rgb(40, 24, 248)'))

trace_lab = Bar(x=parties.index,
                y=parties['Labour Party'],
                name='Labour',
                marker=dict(color='rgb(252, 20, 20)'))

trace_lib = Bar(x=parties.index,
                y=parties['Liberal Democrats'],
                name='Lib Dems',
                marker=dict(color='rgb(246, 246, 26)'))

trace_gre = Bar(x=parties.index,
                y=parties['Green Party'],
                name='Green Party',
                marker=dict(color='rgb(26, 154, 29)'))

trace_snp = Bar(x=parties.index,
                y=parties['Scottish National Party'],
                name='SNP',
                marker=dict(color='rgb(238, 132, 16)'))

trace_uki = Bar(x=parties.index,
                y=parties['UK Independence Party'],
                name='UKIP',
                marker=dict(color='rgb(133, 52, 240)'))

data = [trace_con, trace_lab, trace_lib, trace_gre, trace_snp, trace_uki]

layout = Layout(title="Parties Popularity - Google Trends",
                xaxis=dict(title='Date'),
                yaxis=dict(title='Relative number of searches per party'))

fig = Figure(data=data, layout=layout)

py.iplot(fig)

In [359]:
niparties = parties.reset_index()

In [360]:
niparties

,date,Conservative Party,Labour Party,Liberal Democrats,Green Party,Scottish National Party,UK Independence Party
0,2017-04-18,100,19,23,6,12,4
1,2017-04-19,42,14,19,4,10,3
2,2017-04-20,23,18,10,5,8,3
3,2017-04-21,17,12,8,4,6,2
4,2017-04-22,15,11,6,3,6,3
5,2017-04-23,15,14,7,3,6,5
6,2017-04-24,12,10,7,4,6,6
7,2017-04-25,13,8,8,4,6,3
8,2017-04-26,15,10,7,4,6,2
9,2017-04-27,13,11,5,5,5,2
10,2017-04-28,11,6,4,3,5,3
11,2017-04-29,11,7,4,3,5,4
12,2017-04-30,20,6,4,3,5,2
13,2017-05-01,20,7,3,4,5,2
14,2017-05-02,20,7,4,4,5,2
15,2017-05-03,25,8,7,5,6,2
16,2017-05-04,19,9,7,7,7,3
17,2017-05-05,21,11,6,6,12,12
18,2017-05-06,13,8,4,4,8,4
19,2017-05-07,14,8,3,3,5,2
20,2017-05-08,16,9,6,5,6,3
21,2017-05-09,27,16,5,6,5,2
22,2017-05-10,21,11,4,8,6,2
23,2017-05-11,16,12,5,5,5,3
24,2017-05-12,19,14,7,4,6,2
25,2017-05-13,14,10,4,3,4,2
26,2017-05-14,13,10,4,3,5,2
27,2017-05-15,23,16,5,4,6,2
28,2017-05-16,16,22,6,3,5,2
29,2017-05-17,17,12,14,4,6,2
30,2017-05-18,27,12,11,7,7,5
31,2017-05-19,22,13,7,6,6,4

In [368]:
from pandas.tseries.frequencies import to_offset

In [379]:
niparties['date'] = pd.to_datetime(niparties['date'])

In [384]:
niparties.index = niparties['date']

In [390]:
rparties = niparties.resample('7D').sum()

In [670]:
rparties

,Conservative Party,Labour Party,Liberal Democrats,Green Party,Scottish National Party,UK Independence Party
date,,,,,,
2017-04-18,224,98,80,29,54,26
2017-04-25,103,55,35,26,37,18
2017-05-02,128,60,37,34,49,28
2017-05-09,133,89,34,33,37,15
2017-05-16,82,59,38,20,24,13

In [674]:
testparties = rparties.reset_index()

In [676]:
testparties

,date,Conservative Party,Labour Party,Liberal Democrats,Green Party,Scottish National Party,UK Independence Party
0,2017-04-18,224,98,80,29,54,26
1,2017-04-25,103,55,35,26,37,18
2,2017-05-02,128,60,37,34,49,28
3,2017-05-09,133,89,34,33,37,15
4,2017-05-16,82,59,38,20,24,13

In [490]:
uparties = rparties.unstack()

In [558]:
uparties

                         date
Conservative Party       2017-04-18    224
                         2017-04-25    103
                         2017-05-02    128
                         2017-05-09    133
                         2017-05-16     82
Labour Party             2017-04-18     98
                         2017-04-25     55
                         2017-05-02     60
                         2017-05-09     89
                         2017-05-16     59
Liberal Democrats        2017-04-18     80
                         2017-04-25     35
                         2017-05-02     37
                         2017-05-09     34
                         2017-05-16     38
Green Party              2017-04-18     29
                         2017-04-25     26
                         2017-05-02     34
                         2017-05-09     33
                         2017-05-16     20
Scottish National Party  2017-04-18     54
                         2017-04-25     37
                         2017-05-02     49
                         2017-05-09     37
                         2017-05-16     24
UK Independence Party    2017-04-18     26
                         2017-04-25     18
                         2017-05-02     28
                         2017-05-09     15
                         2017-05-16     13
dtype: int32

In [559]:
urparty = DataFrame(uparties).reset_index()

In [560]:
urparty

                    level_0       date    0
0        Conservative Party 2017-04-18  224
1        Conservative Party 2017-04-25  103
2        Conservative Party 2017-05-02  128
3        Conservative Party 2017-05-09  133
4        Conservative Party 2017-05-16   82
5              Labour Party 2017-04-18   98
6              Labour Party 2017-04-25   55
7              Labour Party 2017-05-02   60
8              Labour Party 2017-05-09   89
9              Labour Party 2017-05-16   59
10        Liberal Democrats 2017-04-18   80
11        Liberal Democrats 2017-04-25   35
12        Liberal Democrats 2017-05-02   37
13        Liberal Democrats 2017-05-09   34
14        Liberal Democrats 2017-05-16   38
15              Green Party 2017-04-18   29
16              Green Party 2017-04-25   26
17              Green Party 2017-05-02   34
18              Green Party 2017-05-09   33
19              Green Party 2017-05-16   20
20  Scottish National Party 2017-04-18   54
21  Scottish National Party 2017-04-25   37
22  Scottish National Party 2017-05-02   49
23  Scottish National Party 2017-05-09   37
24  Scottish National Party 2017-05-16   24
25    UK Independence Party 2017-04-18   26
26    UK Independence Party 2017-04-25   18
27    UK Independence Party 2017-05-02   28
28    UK Independence Party 2017-05-09   15
29    UK Independence Party 2017-05-16   13

In [561]:
uparties_col = ['Party', 'Date', 'Searches']
urparty.columns = uparties_col

In [570]:
urparty.set_index(['Party'])

                              Date  Searches
Party
Conservative Party      2017-04-18       224
Conservative Party      2017-04-25       103
Conservative Party      2017-05-02       128
Conservative Party      2017-05-09       133
Conservative Party      2017-05-16        82
Labour Party            2017-04-18        98
Labour Party            2017-04-25        55
Labour Party            2017-05-02        60
Labour Party            2017-05-09        89
Labour Party            2017-05-16        59
Liberal Democrats       2017-04-18        80
Liberal Democrats       2017-04-25        35
Liberal Democrats       2017-05-02        37
Liberal Democrats       2017-05-09        34
Liberal Democrats       2017-05-16        38
Green Party             2017-04-18        29
Green Party             2017-04-25        26
Green Party             2017-05-02        34
Green Party             2017-05-09        33
Green Party             2017-05-16        20
Scottish National Party 2017-04-18        54
Scottish National Party 2017-04-25        37
Scottish National Party 2017-05-02        49
Scottish National Party 2017-05-09        37
Scottish National Party 2017-05-16        24
UK Independence Party   2017-04-18        26
UK Independence Party   2017-04-25        18
UK Independence Party   2017-05-02        28
UK Independence Party   2017-05-09        15
UK Independence Party   2017-05-16        13

In [574]:
gf.groups

{'Conservative Party': Int64Index([0, 1, 2, 3, 4], dtype='int64'),
 'Green Party': Int64Index([15, 16, 17, 18, 19], dtype='int64'),
 'Labour Party': Int64Index([5, 6, 7, 8, 9], dtype='int64'),
 'Liberal Democrats': Int64Index([10, 11, 12, 13, 14], dtype='int64'),
 'Scottish National Party': Int64Index([20, 21, 22, 23, 24], dtype='int64'),
 'UK Independence Party': Int64Index([25, 26, 27, 28, 29], dtype='int64')}

In [575]:
gf.head()

                      Party       Date  Searches
0        Conservative Party 2017-04-18       224
1        Conservative Party 2017-04-25       103
2        Conservative Party 2017-05-02       128
3        Conservative Party 2017-05-09       133
4        Conservative Party 2017-05-16        82
5              Labour Party 2017-04-18        98
6              Labour Party 2017-04-25        55
7              Labour Party 2017-05-02        60
8              Labour Party 2017-05-09        89
9              Labour Party 2017-05-16        59
10        Liberal Democrats 2017-04-18        80
11        Liberal Democrats 2017-04-25        35
12        Liberal Democrats 2017-05-02        37
13        Liberal Democrats 2017-05-09        34
14        Liberal Democrats 2017-05-16        38
15              Green Party 2017-04-18        29
16              Green Party 2017-04-25        26
17              Green Party 2017-05-02        34
18              Green Party 2017-05-09        33
19              Green Party 2017-05-16        20
20  Scottish National Party 2017-04-18        54
21  Scottish National Party 2017-04-25        37
22  Scottish National Party 2017-05-02        49
23  Scottish National Party 2017-05-09        37
24  Scottish National Party 2017-05-16        24
25    UK Independence Party 2017-04-18        26
26    UK Independence Party 2017-04-25        18
27    UK Independence Party 2017-05-02        28
28    UK Independence Party 2017-05-09        15
29    UK Independence Party 2017-05-16        13

In [573]:
parties = ['Conservative Party', 'Labour Party', 'Liberal Democrats', 'Green Party', 'Scottish National Party', 'UK Independence Party']
fill_colors = ['#66c2a5', '#fc8d62', '#8da0cb', '#e78ac3', '#a6d854', '#66c2a5']
gf = urparty.groupby('Party')

data = []

for party, fill_color in zip(urparty[::-1], fill_colors):
    group = gf.get_group(party)
    days = group['Date'].tolist()
    length = len(days)
    party_coords = [party] * length
    searches = group['Searches'].tolist()
    zeros = [0] * length
    
    data.append(dict(
        type='scatter3d',
        mode='lines',
        x=days + days[::-1] + [days[0]],  # year loop: in incr. order then in decr. order then years[0]
        y=party_coords * 2 + [party_coords[0]],
        z=searches + zeros + [searches[0]],
        name='',
        surfaceaxis=1, # add a surface axis ('1' refers to axes[1] i.e. the y-axis)
        surfacecolor=fill_color,
        line=dict(
            color='black',
            width=4
        ),
    ))

layout = dict(
    title='Relative number of searches per party',
    showlegend=False,
    scene=dict(
        xaxis=dict(title=''),
        yaxis=dict(title=''),
        zaxis=dict(title=''),
        camera=dict(
            eye=dict(x=-1.7, y=-1.7, z=0.5)
        )
    )
)

fig = dict(data=data, layout=layout)
py.iplot(fig)

KeyError: 'Party'

In [539]:
aparties

Conservative Party         134.0
Labour Party                72.2
Liberal Democrats           44.8
Green Party                 28.4
Scottish National Party     40.2
UK Independence Party       20.0
dtype: float64

In [436]:
aparties = rparties.mean()

In [438]:
DataFrame(aparties)

                             0
Conservative Party       134.0
Labour Party              72.2
Liberal Democrats         44.8
Green Party               28.4
Scottish National Party   40.2
UK Independence Party     20.0

In [391]:
trace_con = Bar(x=rparties.index,
                  y=rparties['Conservative Party'],
                  name='Conservatives',
                  marker=dict(color='rgb(40, 24, 248)'))

trace_lab = Bar(x=rparties.index,
                y=rparties['Labour Party'],
                name='Labour',
                marker=dict(color='rgb(252, 20, 20)'))

trace_lib = Bar(x=rparties.index,
                y=rparties['Liberal Democrats'],
                name='Lib Dems',
                marker=dict(color='rgb(246, 246, 26)'))

trace_gre = Bar(x=rparties.index,
                y=rparties['Green Party'],
                name='Green Party',
                marker=dict(color='rgb(26, 154, 29)'))

trace_snp = Bar(x=rparties.index,
                y=rparties['Scottish National Party'],
                name='SNP',
                marker=dict(color='rgb(238, 132, 16)'))

trace_uki = Bar(x=rparties.index,
                y=rparties['UK Independence Party'],
                name='UKIP',
                marker=dict(color='rgb(133, 52, 240)'))

data = [trace_con, trace_lab, trace_lib, trace_gre, trace_snp, trace_uki]

layout = Layout(title="Parties Popularity - Google Trends",
                xaxis=dict(title='Date'),
                yaxis=dict(title='Relative number of searches per party'))

fig = Figure(data=data, layout=layout)

py.iplot(fig)

In [545]:
import plotly.plotly as py
import plotly.graph_objs as go